version: '3'

services:
  db:
    build:
      context: .
      dockerfile: ./docker/pgsql.dockerfile
    container_name: postgresql
    hostname: kite.cs.miyazaki-u.ac.jp
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
      POSTGRES_USER: dbuser06
      POSTGRES_PASSWORD: dbpass06
      POSTGRES_DB: db06
      POSTGRES_HOST_AUTH_METHOD:
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./sample_data:/data
      - ./table_create:/table
    restart: always

  c_dev:
    build:
      context: .
      dockerfile: ./docker/ubuntu.dockerfile
    container_name: c_dev
    ports:
      - "10000:10000"
    volumes:
      - ../libpq_program:/libpq_program
    tty: true
    restart: always
